name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel toml

      - name: Build wheels
        run: |
          chmod +x ./.github/scripts/build.sh
          ./.github/scripts/build.sh

      - name: Install package and dev dependencies
        run: |
          pip install --upgrade pip
          pip install ".[dev]"
          pip install pytest-cov

      - name: Export env vars from secret JSON
        env:
          INTEGRATION_TEST_CONFIG: ${{ secrets.INTEGRATION_TEST_CONFIG }}  # Your secret containing JSON with env vars
        run: |
          echo "$INTEGRATION_TEST_CONFIG" > env.json
          python -c "
          import json, os
          with open('env.json') as f:
            envs = json.load(f)
          for k, v in envs.items():
            # Export each env var for the rest of the job
            print(f'::add-mask::{v}')  # mask secret values in logs
            os.environ[k] = v
            print(f'::set-env name={k}::{v}')
          "
          # Note: 'set-env' is deprecated; use `echo "{name}={value}" >> $GITHUB_ENV` instead
          # So better:
          with open('env.json') as f:
            envs = json.load(f)
          for k,v in envs.items():
            print(f'{k}={v}', file=open(os.environ["GITHUB_ENV"], "a"))

      - name: Run integration tests
        run: |
          pytest -vv tests/integration