name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel toml

      - name: Build wheels
        run: |
          chmod +x ./.github/scripts/build.sh
          ./.github/scripts/build.sh

      - name: Install package and dev dependencies
        run: |
          pip install --upgrade pip
          pip install ".[dev]"
          pip install pytest-cov

      - name: Decode ENV JSON and write to .env
        run: |
          echo "$INTEGRATION_TEST_CONFIG" | jq -r 'to_entries[] | "\(.key)=\(.value)"' > .env

      - name: Export variables from .env
        run: |
          set -a
          source .env
          set +a
      
      - name: Run integration tests
        run: |
          pytest -vv tests/integration