name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Export env vars from secret JSON
        env:
          INTEGRATION_TEST_CONFIG: ${{ secrets.INTEGRATION_TEST_CONFIG }}
        run: |
          echo "$INTEGRATION_TEST_CONFIG" > env.json
          python <<EOF
          import json, os

          with open('env.json') as f:
              envs = json.load(f)

          with open(os.environ['GITHUB_ENV'], 'a') as env_file:
              for k, v in envs.items():
                  print(f'::add-mask::{v}')  # mask secret values in logs
                  env_file.write(f'{k}={v}\n')
        

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel toml

      - name: Build wheels
        run: |
          chmod +x ./.github/scripts/build.sh
          ./.github/scripts/build.sh

      - name: Install package and dev dependencies
        run: |
          pip install --upgrade pip
          pip install ".[dev]"
          pip install pytest-cov



      - name: Run integration tests
        run: |
          pytest -vv tests/integration