name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Export env vars from secret JSON
        env:
          INTEGRATION_TEST_CONFIG: ${{ secrets.INTEGRATION_TEST_CONFIG }}
        run: |
          echo "$INTEGRATION_TEST_CONFIG" > env.json
          python <<EOF
          import json, os

          with open('env.json') as f:
              envs = json.load(f)

          with open(os.environ['GITHUB_ENV'], 'a') as env_file:
              for k, v in envs.items():
                  print(f'::add-mask::{v}')  # mask secret values in logs
                  env_file.write(f'{k}={v}\n')

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel toml

      - name: Build wheels
        run: |
          chmod +x ./.github/scripts/build.sh
          ./.github/scripts/build.sh

      - name: Install package and dev dependencies
        run: |
          pip install --upgrade pip
          pip install ".[dev]"

      - name: Run integration tests
        id: run-tests
        run: |
          set -o pipefail

          # Run tests and capture output
          pytest tests/integration --tb=short | tee result.log
          TEST_EXIT_CODE=${PIPESTATUS[0]}

          # Extract failed tests (only if there are failures)
          if [ $TEST_EXIT_CODE -ne 0 ]; then
            grep -E 'FAILED.*::' result.log | cut -d ':' -f 1 | sort | uniq > failed_files.txt
          fi

          echo "test_exit_code=$TEST_EXIT_CODE" >> $GITHUB_ENV
          
          # Show failed files if any
          if [ -f failed_files.txt ]; then
            echo "Failed test files:"
            cat failed_files.txt
          fi

          # Important: Exit with the original test exit code
          exit $TEST_EXIT_CODE

      - name: Add Failed Files to Summary (Table)
        if: failure() || cancelled()
        run: |
          {
            echo "### ❌ Integration Tests Failed"
            echo ""
            if [ -f failed_files.txt ] && [ -s failed_files.txt ]; then
              echo "| Failed Test Files |"
              echo "|------------------|"
              while read -r file; do
                echo "| $file |"
              done < failed_files.txt
            else
              echo "⚠️ Test execution failed but no specific test failures were detected"
            fi
          } >> $GITHUB_STEP_SUMMARY

      - name: Add Success Summary
        if: success()
        run: |
          echo "### ✅ All integration tests passed!" >> $GITHUB_STEP_SUMMARY

      - name: Upload Failed Files Summary
        if: failure() || cancelled()
        uses: actions/upload-artifact@v4
        with:
          name: failed-test-files
          path: |
            failed_files.txt
            result.log
          retention-days: 7