name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install toml
        run: pip install toml

      - name: Install pytest
        run: pip install pytest

      - name: Run unit tests with coverage
        run: |
          pytest --cov=./ --cov-report=term --cov-report=xml tests/unit

      - name: Upload coverage to GitHub summary
        if: always()
        run: |
          echo '### Pytest Coverage Report' >> $GITHUB_STEP_SUMMARY
          coverage report >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml