name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel toml

      - name: Build wheels
        run: |
          chmod +x ./.github/scripts/build.sh
          ./.github/scripts/build.sh

      - name: Install package and test dependencies
        run: |
          pip install dist/*.whl
          pip install pytest pytest-cov
          # pip install -r requirements.txt  # Uncomment if you have requirements.txt

      - name: Run unit tests with coverage
        run: |
          pytest -vv tests/unit